server:
  port: 5000
  tomcat:
    use-relative-redirects: true
  ssl:
    key-store: "src/main/resources/keystore.jks"
    key-store-password: "kurento"
    key-store-type: "JKS"
    key-alias: "kurento-selfsigned"

logging:
  level:
    org:
      springframework:
        security: INFO
        web:
          filter:
            CommonsRequestLoggingFilter: INFO